### ISSUE TITLE
TODO & SKIP implementation

### ISSUE THREAD

**Issue by keidrych** [KayleePop/muggle#1]
Excellent lightweight library, used and recommended for both Development and Production testing.

If you could support the TODO & SKIP directives long-term use would be more sustainable. https://testanything.org/tap-specification.html

Ideally a syntactical such as `.only` would also be great to avoid running all tests in the file.

**Comment by KayleePop** [comment]
> Excellent lightweight library, used and recommended for both Development and Production testing.

Thanks! :smiley: 

You can just add '# SKIP' and '# TODO' to the test names like this and it will be parsed correctly

```js
const test = require('muggle-test')

test('# TODO unimplemented test', () => {})

if (!window) {
  test('browser test # SKIP browser only', () => {})
} else {
  test('browser test', () => {
    // test that only runs in browser
  }
}
```

Just make sure to have a space after the pound sign and use all caps for SKIP and TODO.

You can also quickly and easily hack a .only() together by swapping the normal test variable for an empty function and using a new variable for the tests you want to isolate. like this

```js
const test = () => {}
const testOnly = require('muggle-test')

test('test 1', () => {})

test('test 2', () => {})

testOnly('only this test will be run', () => {})
```

You could also copy the tests into a new file or select and comment out the other tests in an editor with `CTRL + /`

I'd rather not add any complexity to the API or code at all. I played with adding both of these as features, but it didn't seem worth it when there are easy workarounds.

**Comment by KayleePop** [comment]
v1.1.0 has todo and skip like this

```js
test('skipped test', () => {
	// only runs in browser
}, { skip: window ? false : 'browser only' })

test('incomplete test', () => {
	function sum () {}
	assert(sum(3, 2), 5)
}, { todo: 'implement sum()' })
```
